server:
  port: 8090


oss:
  gitee:
    enabled: true
    access-token: ENC(e7w7coXyohDyI36gMQFUU0z/2x2J3k8mV3HhfrQEkLYUCE9CfH7sSU+u/bLq9mNR+7alvo8MZk3K9WvNW7qVT3ecMz1Mo9wpdOJ6NzSzbfQ=)
    owner: rouxin
    repo: image_vector
  gitcode:
    enable: true
    private-token: ENC(j5pUI1Nk8JoqcA+REpcPFy0DsofOV6WxHxUvUkWD4sG5KKKx6jIobpTudcevxGjRGa3gZ3SjSbP8Bj+rhX6usA==)
    id: 255523
    branch: master
  github:
    enable: true
    authorization: ENC(x0fyWIFklRbVGk4wntIMKEof6b28IOcl/DaDvW+xcRr8cV7w8SbE9N/uG6GpZzt2HZdcfqotUXe8+gTt5o6Ib060EVrjD9eagWBRW6QXxJA=)
    owner: roukaixin
    repo: image_vector
    branch: main
spring:
  servlet:
    multipart:
      max-file-size: 5MB
  profiles:
    active: pro # 激活那个环境
